stages:
  - test
  - build
  - publish

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits-signoffs.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-build.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

test:check-python3-formatting:
  stage: test
  needs: []
  image: python:3
  before_script:
    - pip install tox
  script:
    - TOXENV=flake8 tox

build:docker:
  variables:
    DOCKER_REPOSITORY: mendersoftware/mantra-api
  only:
    changes:
      - tetra/**/*
      - setup.py
      - etc/tetra/tetra.conf.sample

publish:image:
  variables:
    DOCKER_REPOSITORY: mendersoftware/mantra-api
  only:
    changes:
      - tetra/**/*
      - setup.py
      - etc/tetra/tetra.conf.sample

build:docker:ui:
  extends: build:docker
  variables:
    DOCKER_REPOSITORY: mendersoftware/mantra-ui
    DOCKER_DIR: ui
  only:
    changes:
      - ui/**/*

publish:image:ui:
  extends: publish:image
  dependencies:
    - build:docker:ui
  variables:
    DOCKER_REPOSITORY: mendersoftware/mantra-ui
    DOCKER_DIR: ui
  only:
    changes:
      - ui/**/*
