sudo: required

services:
    - docker

language: python
python:
    - "2.7"

env:
    - TOXENV=flake8
    - TOXENV=functional

install: "pip install tox"

before_script:
    - ./travis-setup.sh

script: tox

notifications:
    email: false
