services:
    - postgresql
    # rabbitmq needs sudo in travis, but sudo makes travis checks take forever.
    # instead, run celery on redis since it doesn't need sudo. hopefully this
    # will work fine, but it may become an issue since we want to use rabbitmq
    - redis-server

language: python
python:
    - "2.7"

env:
    - TOXENV=flake8
    - TOXENV=functional

install: "pip install tox"

before_script:
    - ./travis-setup.sh

script: tox

notifications:
    email: false
