version: '2'
services:
  api:
    volumes:
      - .:/tetra
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui/:/work
      - /work/node_modules
      - /work/dist
