version: '2'
services:
  api:
    image: tetra-api
    container_name: tetra-api
    depends_on:
      - db
    links:
      - db
    command: |
      bash -c "export PYTHONUNBUFFERED=1 && gunicorn --reload -t 120 --bind 0.0.0.0:7374 --access-logfile - tetra.app:application"
    ports:
      - "7374:7374"
  worker:
    image: tetra-api
    container_name: tetra-worker
    depends_on:
      - queue
    links:
      - queue
    # celery has a `--auotreload` flag that doesn't reload dependent modules,
    # so it doesn't work. use `docker-compose restart worker` instead.
    command: |
      su -m tetra-worker -c "celery --app=tetra.worker.app worker --loglevel=INFO"
  db:
    image: bitnami/postgresql:12.2.0
    container_name: tetra-db
    ports:
      # note: exposing port 5432 here causes issues in travis builds
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tetra-db
  queue:
    image: bitnami/rabbitmq:3.8.2-debian-10-r25
    container_name: tetra-queue
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: tetra
      RABBITMQ_DEFAULT_PASS: password
  ui:
    image: tetra-ui
    container_name: tetra-ui
    ports:
      - "8080:80"
    depends_on:
      - api
  gateway:
    image: nginx:stable-alpine
    container_name: tetra-gateway
    entrypoint: >
      /bin/sh -c 'echo "
      events {}
      http {
        server {
          location / {
            proxy_max_temp_file_size 128m;
            proxy_buffers 16 16k;
            proxy_buffer_size 16k;
            proxy_pass http://ui:80;
          }
          location ~* /api/(.*) {
            proxy_max_temp_file_size 128m;
            proxy_buffers 16 16k;
            proxy_buffer_size 16k;
            rewrite ^/api(.*)$$ \$$1 break;
            proxy_pass http://api:7374;
          }
        }
      }" > /etc/nginx/nginx.conf && nginx -g "daemon off;"
      '
    ports:
      # The HTTP port
      - "80:80"
    depends_on:
      - ui
      - api
