version: '2'
services:
  api:
    build: .
    image: tetra-api
    ports:
      - "7374:7374"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:9.5
    container_name: tetra-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tetra-db
