version: '2'
services:
  api:
    restart: always
    label:
      - "traefik.http.middlewares.auth.basicauth.users=$TETRA_USERNAME:$TETRA_PASSWORD"
  worker:
    restart: always
  queue:
    restart: always
  db:
    restart: always
  ui:
    restart: always
  gateway:
    restart: always
