version: '2'
services:
  api:
    build: .
    restart: always
  worker:
    build: .
    restart: always
  queue:
    restart: always
  db:
    restart: always
  ui:
    build:
      context: ./ui
    restart: always
  gateway:
    restart: always
