version: '2'
services:
  api:
    build: .
    restart: always
    labels:
      - "traefik.http.middlewares.auth.basicauth.users=$TETRA_USERNAME:$TETRA_PASSWORD"
  worker:
    build: .
    restart: always
  queue:
    restart: always
  db:
    restart: always
  ui:
    build:
      context: ./ui
    restart: always
    labels:
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
  gateway:
    restart: always
